# Based on:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow
name: Release Python Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test and build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
      - name: Install package
        run: pip install .
      - name: Test with pytest
        run: |
          pytest
      - name: Build source distribution and wheel files
        run: python -m build
      - name: Extract version
        run: echo "PMC_VERSION=$(grep "^VERSION.*" setup.py | cut -d " " -f 3)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ env.PMC_VERSION }}
